create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  "enrollmentNo" text not null unique,
  "rollNo" text not null unique,
  branch text not null,
  year text not null,
  phone text not null,
  email text default '',
  city text default '',
  created_at timestamptz not null default now()
);

alter table public.students enable row level security;

drop policy if exists "Public can read students" on public.students;
drop policy if exists "Public can insert students" on public.students;
drop policy if exists "Public can update students" on public.students;
drop policy if exists "Public can delete students" on public.students;

create policy "Public can read students" on public.students for select to anon using (true);
create policy "Public can insert students" on public.students for insert to anon with check (true);
create policy "Public can update students" on public.students for update to anon using (true) with check (true);
create policy "Public can delete students" on public.students for delete to anon using (true);
