-- Run this in Supabase SQL Editor.
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  "enrollmentNo" text not null unique,
  name text not null,
  "rollNo" text not null unique,
  branch text not null,
  year text not null,
  phone text not null,
  email text default '',
  city text default '',
  created_at timestamptz not null default now()
);

alter table public.students enable row level security;

create policy "public read students"
on public.students for select
to anon, authenticated
using (true);

create policy "public insert students"
on public.students for insert
to anon, authenticated
with check (true);

create policy "public update students"
on public.students for update
to anon, authenticated
using (true)
with check (true);

create policy "public delete students"
on public.students for delete
to anon, authenticated
using (true);
